variables:
  dockerVersion: '19.03.5'
  dotnetVersion: '3.1.x'

trigger:
- master
- development

pr:
- master
- development

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DockerInstaller@0
  inputs:
    dockerVersion: $(dockerVersion)
  displayName: 'Docker: Install - $(dockerVersion)'

- task: UseDotNet@2
  displayName: 'Use DotNet Core $(dotnetVersion)'
  inputs:
    packageType: 'sdk'
    version: $(dotnetVersion)
    includePreviewVersions: false

- script: docker-compose -f "docker-compose.integration.yml" up --build -d
  displayName: 'Docker-compose up'

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: test
    projects: '**/*API.Tests/*.csproj'
    arguments: '-v n  --collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: 'Run Integration tests'
  inputs:
    command: test
    projects: '**/*Integration.Tests/*.csproj'
    arguments: '-v n'

- task: DockerCompose@0
  displayName: 'Build: Dev'
  inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'NHSAPP-BuyingCatalogue (Non-Prod)'
      azureContainerRegistry: '{"loginServer":"gpitfuturesdevacr.azurecr.io", "id" : "/subscriptions/7b12a8a2-f06f-456f-b6f9-aa2d92e0b2ec/resourceGroups/gpitfutures-dev-rg-acr/providers/Microsoft.ContainerRegistry/registries/gpitfuturesdevacr"}'
      dockerComposeFile: '**/docker-compose-build.yml'
      action: 'Build services'
      additionalImageTags: '$(Build.BuildNumber)'
      includeSourceTags: true

- task: DockerCompose@0
  displayName: 'Docker Build: Test'
  condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
  inputs:
    azureSubscription: 'NHSAPP-BuyingCatalogue (Non-Prod)'
    azureContainerRegistry: '{"loginServer":"gpitfuturestestacr.azurecr.io", "id" : "/subscriptions/7b12a8a2-f06f-456f-b6f9-aa2d92e0b2ec/resourceGroups/gpitfutures-test-rg-acr/providers/Microsoft.ContainerRegistry/registries/gpitfuturestestacr"}'
    dockerComposeFile: '**/docker-compose-build.yml'
    action: 'Build services'

- task: DockerCompose@0
  displayName: 'Docker Build: Pre-Prod'
  condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
  inputs:
    azureSubscription: 'NHSAPP-BuyingCatalogue (Non-Prod)'
    azureContainerRegistry: '{"loginServer":"gpitfuturespprodacr.azurecr.io", "id" : "/subscriptions/7b12a8a2-f06f-456f-b6f9-aa2d92e0b2ec/resourceGroups/gpitfutures-pprod-rg-acr/providers/Microsoft.ContainerRegistry/registries/gpitfuturespprodacr"}'
    dockerComposeFile: '**/docker-compose-build.yml'
    action: 'Build services'

- task: DockerCompose@0
  displayName: 'Docker Build: Prod'
  condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
  inputs:
    azureSubscription: 'NHSAPP-BuyingCatalogue (Prod)'
    azureContainerRegistry: '{"loginServer":"gpitfuturesprodacr.azurecr.io", "id" : "/subscriptions/d1be8dbc-1a9f-4b7b-ba51-037116110e00/resourceGroups/gpitfutures-prod-rg-acr/providers/Microsoft.ContainerRegistry/registries/gpitfuturesprodacr"}'
    dockerComposeFile: '**/docker-compose-build.yml'
    action: 'Build services'

- task: DockerCompose@0
  displayName: 'Docker Push: Dev'
  condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
  inputs:
    azureSubscription: 'NHSAPP-BuyingCatalogue (Non-Prod)'
    azureContainerRegistry: '{"loginServer":"gpitfuturesdevacr.azurecr.io", "id" : "/subscriptions/7b12a8a2-f06f-456f-b6f9-aa2d92e0b2ec/resourceGroups/gpitfutures-dev-rg-acr/providers/Microsoft.ContainerRegistry/registries/gpitfuturesdevacr"}'
    dockerComposeFile: '**/docker-compose-build.yml'
    action: 'Push services'
    additionalImageTags: '$(Build.BuildNumber)'
    includeSourceTags: true

- task: DockerCompose@0
  displayName: 'Docker Push: Test'
  condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
  inputs:
    azureSubscription: 'NHSAPP-BuyingCatalogue (Non-Prod)'
    azureContainerRegistry: '{"loginServer":"gpitfuturestestacr.azurecr.io", "id" : "/subscriptions/7b12a8a2-f06f-456f-b6f9-aa2d92e0b2ec/resourceGroups/gpitfutures-test-rg-acr/providers/Microsoft.ContainerRegistry/registries/gpitfuturestestacr"}'
    dockerComposeFile: '**/docker-compose-build.yml'
    action: 'Push services'

- task: DockerCompose@0
  displayName: 'Docker Push: Pre-Prod'
  condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
  inputs:
    azureSubscription: 'NHSAPP-BuyingCatalogue (Non-Prod)'
    azureContainerRegistry: '{"loginServer":"gpitfuturespprodacr.azurecr.io", "id" : "/subscriptions/7b12a8a2-f06f-456f-b6f9-aa2d92e0b2ec/resourceGroups/gpitfutures-pprod-rg-acr/providers/Microsoft.ContainerRegistry/registries/gpitfuturespprodacr"}'
    dockerComposeFile: '**/docker-compose-build.yml'
    action: 'Push services'

- task: DockerCompose@0
  displayName: 'Docker Push: Prod'
  condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
  inputs:
    azureSubscription: 'NHSAPP-BuyingCatalogue (Prod)'
    azureContainerRegistry: '{"loginServer":"gpitfuturesprodacr.azurecr.io", "id" : "/subscriptions/d1be8dbc-1a9f-4b7b-ba51-037116110e00/resourceGroups/gpitfutures-prod-rg-acr/providers/Microsoft.ContainerRegistry/registries/gpitfuturesprodacr"}'
    dockerComposeFile: '**/docker-compose-build.yml'
    action: 'Push services'

- script: docker-compose -f "docker-compose.integration.yml" down -v
  displayName: 'Docker-compose down'