variables:
  dockerVersion: '19.03.5'
  dotnetVersion: '3.1.x'

trigger:
- master
- development

pr:
- master
- development

pool:
  name: GP IT Futures AKS Build Agents

steps:

- task: DockerInstaller@0
  inputs:
    dockerVersion: $(dockerVersion)
  displayName: 'Docker: Install - $(dockerVersion)'

- task: UseDotNet@2
  displayName: 'Use DotNet Core $(dotnetVersion)'
  inputs:
    packageType: 'sdk'
    version: $(dotnetVersion)
    includePreviewVersions: false

- script: |
    docker-compose -f "docker-compose.integration.yml" up --build -d
  displayName: 'Docker-compose up'

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: test
    projects: '**/*API.Tests/*.csproj'
    arguments: '-v n  --collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: 'Run Integration tests'
  inputs:
    command: test
    projects: '**/*Integration.Tests/*.csproj'
    arguments: '-v n'

- task: DockerCompose@0
  displayName: 'Build: Dev'
  inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'NHSAPP-BuyingCatalogue (Non-Prod)'
      azureContainerRegistry: '{"loginServer":"gpitfuturesdevacr.azurecr.io", "id" : "/subscriptions/7b12a8a2-f06f-456f-b6f9-aa2d92e0b2ec/resourceGroups/gpitfutures-dev-rg-acr/providers/Microsoft.ContainerRegistry/registries/gpitfuturesdevacr"}'
      dockerComposeFile: '**/docker-compose-build.yml'
      action: 'Build services'
      additionalImageTags: '$(Build.BuildNumber)'
      includeSourceTags: true

- task: DockerCompose@0
  displayName: 'Push: Dev'
  inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'NHSAPP-BuyingCatalogue (Non-Prod)'
      azureContainerRegistry: '{"loginServer":"gpitfuturesdevacr.azurecr.io", "id" : "/subscriptions/7b12a8a2-f06f-456f-b6f9-aa2d92e0b2ec/resourceGroups/gpitfutures-dev-rg-acr/providers/Microsoft.ContainerRegistry/registries/gpitfuturesdevacr"}'
      dockerComposeFile: '**/docker-compose-build.yml'
      action: 'Push services'
      additionalImageTags: '$(Build.BuildNumber)'
      includeSourceTags: true

- script: |
    docker-compose -f "docker-compose.integration.yml" down -v
  displayName: 'Docker-compose down'