version: '3.5'

services:

  nhsd.buyingcatalogue.document.api:
    image: ${REGISTRY:-nhsd}/buying-catalogue/document-api:${TAG:-latest}
    container_name: document_api
    build: 
      context: .
      dockerfile: API.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AZUREBLOBSTORAGE__CONNECTIONSTRING=AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://blob.store:10000/devstoreaccount1;QueueEndpoint=http://blob.store:10001/devstoreaccount1;TableEndpoint=http://blob.store:10002/devstoreaccount1;
      - AZUREBLOBSTORAGE__CONTAINERNAME=container-1
    networks:
      - document_network
    depends_on:
      - blob.store
    ports:
      - "8090:80"
      
  blob.store:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: blob_store
    networks:
      - document_network
    ports:
      - "10000:10000"
      - "10001:10001"
      
  file.upload:
    image: ${REGISTRY:-nhsd}/buying-catalogue/file-uploader:${TAG:-latest}
    build: 
      context: .
      dockerfile: FileUpload.Dockerfile
    container_name: file_uploader
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://blob.store:10000/devstoreaccount1;QueueEndpoint=http://blob.store:10001/devstoreaccount1;TableEndpoint=http://blob.store:10002/devstoreaccount1;
    depends_on:
      - blob.store
    networks:
      - document_network
      
networks: 
  document_network:
    name: document_network
    driver: bridge
