
version: '3.5'

services:

#DocumentService
  nhsd.buyingcatalogue.document.api:
    image: ${REGISTRY:-nhsd}/buying-catalogue/document-dapi:${TAG:-latest}
    container_name: document_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AZUREBLOBSTORAGE__CONNECTIONSTRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZUREBLOBSTORAGE__CONTAINERNAME=${CONTAINER_NAME:-container-1}

#File Upload
  file.upload:
    image: ${REGISTRY:-nhsd}/buying-catalogue/file-uploader:${TAG:-latest}
    container_name: file_uploader
    build:
      context: .
      dockerfile: Dockerfile.fileupload
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
